#!/bin/sh

DIRNAME=$(dirname "$0")
SCRIPT_DIR=$(cd "${DIRNAME}" && pwd)
ROOT_DIR=${SCRIPT_DIR}/..

"${SCRIPT_DIR}/geth" --exec "eth.getBalance('${1}')" attach "${ROOT_DIR}/data/test_chain/geth.ipc"

# address 0xadd1f6f4f593f641a54a66b1b5c80240e4433b6e
